backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: '_media' # Media files will be stored in the repo under static/images/uploads
collections:
  - name: 'pages'
    label: 'Pages'
    folder: '..'
    create: true
    slug: '{{ slug }}'
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
